version: '3.8'

name: 'todomernapp'

services:
  mongo:
    image: mongo:6
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    networks:
      - todomernapp

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - todomernapp
    ports:
      - '8000:8000'
    depends_on:
      - mongo
    command: npm run dev

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - todomernapp
    ports:
      - '5173:5173'
    depends_on:
      - backend

volumes:
  mongo_data:

networks:
  todomernapp:
    driver: bridge
